name: flutter_model
description: A new Flutter project to test Onvif.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  easy_onvif:
    path: ../../
  flutter_loggy: ^2.0.1
  loggy: ^2.0.1+1
  yaml: ^3.1.1
  flutter_vlc_player: ^7.1.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - config.yaml
